"""Forge CLI — start/init/doctor/models (DESIGN.md §8.1)

`python -m src.cli <command>`으로 실행한다 (패키징/entry point는 범위 밖).
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path
from typing import Optional

from .core.registry import Registry
from .providers.base import make_provider
from .settings import (
    ConfigError,
    ProviderConfig,
    TimeoutsConfig,
    VALID_TIERS,
    load_config,
)

# ---------------------------------------------------------------------------
# init — 감지할 provider 후보 (우선순위 순). 값은 DESIGN.md §8.1 명세 그대로.
# ---------------------------------------------------------------------------

_INIT_PROVIDER_TEMPLATES = [
    {
        "name": "nvidia",
        "env": "NVIDIA_API_KEY",
        "litellm_prefix": "openai",
        "api_base": "https://integrate.api.nvidia.com/v1",
    },
    {
        "name": "openrouter",
        "env": "OPENROUTER_API_KEY",
        "litellm_prefix": "openai",
        "api_base": "https://openrouter.ai/api/v1",
    },
    {
        "name": "anthropic",
        "env": "ANTHROPIC_API_KEY",
        "litellm_prefix": "anthropic",
        "api_base": None,
    },
]


def _provider_block_lines(tpl: dict) -> list[str]:
    lines = [f"  - name: {tpl['name']}", f"    litellm_prefix: {tpl['litellm_prefix']}"]
    if tpl["api_base"]:
        lines.append(f"    api_base: {tpl['api_base']}")
    lines.append(f"    api_key_env: {tpl['env']}")
    return lines


def _generate_yaml() -> tuple[str, list[str], bool]:
    """감지된 환경변수 기반 최소 forge.yaml 텍스트를 만든다.

    반환: (yaml 텍스트, 감지된 provider 이름 목록, 키가 하나도 없었는지 여부)
    """
    detected = [t for t in _INIT_PROVIDER_TEMPLATES if os.environ.get(t["env"])]
    no_keys = not detected

    if detected:
        block_lines: list[str] = []
        for t in detected:
            block_lines.extend(_provider_block_lines(t))
        providers_section = "providers:\n" + "\n".join(block_lines)
    else:
        # 키가 전혀 없으면 nvidia 블록을 주석 상태로만 안내 (providers는 빈 리스트로 유효하게 유지)
        example_lines = _provider_block_lines(_INIT_PROVIDER_TEMPLATES[0])
        commented = "\n".join(f"# {line}" for line in example_lines)
        providers_section = (
            "providers: []\n\n"
            "# No provider API key detected in environment\n"
            "# (NVIDIA_API_KEY / OPENROUTER_API_KEY / ANTHROPIC_API_KEY).\n"
            "# Set one, then uncomment and adjust a block like this under providers:\n"
            "#\n" + commented
        )

    yaml_text = (
        "# Forge config generated by `forge init` (schema: src/settings.py)\n"
        "version: 1\n\n"
        "server:\n"
        "  host: 127.0.0.1\n"
        "  port: 4000\n\n"
        "auth:\n"
        "  api_key_env: FORGE_API_KEY\n\n"
        f"{providers_section}\n\n"
        "models: []\n\n"
        "defaults:\n"
        "  capability: 7\n"
        "  tier: tier3\n"
        "  features: [tools, streaming]\n"
    )
    return yaml_text, [t["name"] for t in detected], no_keys


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.config)
    if target.exists() and not args.force:
        print(f"forge: {target} already exists (use --force to overwrite)", file=sys.stderr)
        return 1

    yaml_text, detected, no_keys = _generate_yaml()
    target.write_text(yaml_text, encoding="utf-8")

    try:
        load_config(target)
    except ConfigError as e:
        print(f"forge: generated config failed validation: {e}", file=sys.stderr)
        return 1

    if no_keys:
        print(f"Wrote {target} (no provider API key detected in environment).")
        print(
            "Set NVIDIA_API_KEY, OPENROUTER_API_KEY, or ANTHROPIC_API_KEY, then "
            "uncomment a provider block in the generated file."
        )
    else:
        print(f"Wrote {target} with provider(s): {', '.join(detected)}")
    print("Config validated OK.")
    return 0


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------


def _list_provider_models(
    pconf: ProviderConfig, timeouts: TimeoutsConfig
) -> tuple[bool, int, Optional[str]]:
    """make_provider + list_models() 호출을 실행한다.

    네트워크/구성 실패는 여기서 흡수해 (성공여부, 모델수, 에러요약) 튜플로 반환한다.
    테스트에서는 이 함수를 모킹해 네트워크 없이 doctor 로직을 검증한다.
    """
    try:
        provider = make_provider(pconf, timeouts)
    except Exception as e:  # noqa: BLE001 — provider 생성 실패도 진단 결과로 흡수
        return False, 0, f"{type(e).__name__}: {e}"

    async def _run() -> list[str]:
        try:
            return await provider.list_models()
        finally:
            await provider.close()

    try:
        models = asyncio.run(_run())
    except Exception as e:  # noqa: BLE001
        return False, 0, f"{type(e).__name__}: {e}"
    return True, len(models), None


def _check_provider(pconf: ProviderConfig, timeouts: TimeoutsConfig) -> dict:
    key_configured = pconf.api_key_env is not None
    key_present = bool(pconf.api_key) if key_configured else False

    ok, count, error = _list_provider_models(pconf, timeouts)

    problem = (key_configured and not key_present) or not ok

    return {
        "name": pconf.name,
        "api_key_env": pconf.api_key_env or "-",
        "key_configured": key_configured,
        "key_present": key_present,
        "list_models_ok": ok,
        "model_count": count,
        "error": error,
        "problem": problem,
    }


def cmd_doctor(args: argparse.Namespace) -> int:
    try:
        config = load_config(args.config)
    except ConfigError as e:
        print(f"forge: {e}", file=sys.stderr)
        return 1

    print(f"Config: OK ({args.config})")
    print()

    if not config.providers:
        print("No providers configured.")
        return 0

    results = [_check_provider(p, config.timeouts) for p in config.providers]

    header = "{:<15} {:<22} {:<8} {:<8} {:<8} {}".format(
        "PROVIDER", "KEY_ENV", "KEY_SET", "MODELS", "STATUS", "DETAIL"
    )
    print(header)
    print("-" * len(header))

    any_problem = False
    for r in results:
        if r["problem"]:
            any_problem = True
        if r["key_configured"]:
            key_set = "yes" if r["key_present"] else "no"
        else:
            key_set = "n/a"
        status = "FAIL" if r["problem"] else "OK"
        detail = r["error"] or ""
        print(
            "{:<15} {:<22} {:<8} {:<8} {:<8} {}".format(
                r["name"], r["api_key_env"], key_set, r["model_count"], status, detail
            )
        )

    print()
    if any_problem:
        print("Overall: FAIL - see DETAIL column above.")
        return 1
    print("Overall: OK")
    return 0


# ---------------------------------------------------------------------------
# models
# ---------------------------------------------------------------------------


def cmd_models(args: argparse.Namespace) -> int:
    try:
        config = load_config(args.config)
    except ConfigError as e:
        print(f"forge: {e}", file=sys.stderr)
        return 1

    registry = Registry(config)
    entries = registry.all()
    if args.tier:
        entries = [e for e in entries if e.tier == args.tier]
    entries.sort(key=lambda e: (e.tier, e.id))

    header = "{:<45} {:<7} {:<28} {:<10} {}".format(
        "ID", "TIER", "FEATURES", "CONTEXT", "PRICE ($/1Mtok in,out)"
    )
    print(header)
    print("-" * len(header))
    for e in entries:
        features = ",".join(sorted(e.features))
        context = str(e.context_window) if e.context_window else "-"
        if e.price_per_mtok is None:
            price = "unknown"
        else:
            price = f"{e.price_per_mtok[0]:.2f}/{e.price_per_mtok[1]:.2f}"
        print("{:<45} {:<7} {:<28} {:<10} {}".format(e.id, e.tier, features, context, price))

    print()
    print(f"{len(entries)} model(s). Runtime status (health/cooldown) is at the server's /health.")
    return 0


# ---------------------------------------------------------------------------
# start
# ---------------------------------------------------------------------------


def cmd_start(args: argparse.Namespace) -> int:
    try:
        load_config(args.config)
    except ConfigError as e:
        print(f"forge: {e}", file=sys.stderr)
        return 1

    from .server import create_app  # 지연 import — 다른 커맨드는 서버 스택을 물지 않게

    app = create_app(args.config)
    config = app.state.forge_config

    import uvicorn

    uvicorn.run(app, host=config.server.host, port=config.server.port)
    return 0


# ---------------------------------------------------------------------------
# argparse 배선
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--config", default="forge.yaml", help="Path to forge.yaml (default: forge.yaml)"
    )

    parser = argparse.ArgumentParser(prog="forge", description="Forge AI Gateway CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("start", parents=[common], help="Start the Forge server")

    p_init = sub.add_parser("init", parents=[common], help="Generate a starter forge.yaml")
    p_init.add_argument("--force", action="store_true", help="Overwrite an existing config file")

    sub.add_parser(
        "doctor", parents=[common], help="Diagnose config, API keys, and provider connectivity"
    )

    p_models = sub.add_parser(
        "models", parents=[common], help="List models known to the Registry (offline view)"
    )
    p_models.add_argument("--tier", choices=VALID_TIERS, help="Filter by tier")

    return parser


_COMMANDS = {
    "start": cmd_start,
    "init": cmd_init,
    "doctor": cmd_doctor,
    "models": cmd_models,
}


def main(argv: Optional[list[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return _COMMANDS[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
